apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
