# namespace: tsb-monitoring
createNamespace: true

grafana:
  replicas: 1
  image:
    repository: grafana/grafana
    tag: 9.1.7
  # Additional Grafana configurations

prometheus:
  replicas: 1
  image:
    repository: prom/prometheus
    tag: v2.44.0
