namespace: tsb-monitoring
createNamespace: true

prometheus:
  replicas: 1
  image:
    repository: prom/prometheus
    tag: v2.44.0
  storage:
    size: 10Gi
  serviceAccount: tsb-prometheus
  # Remove scrapeInterval, evaluationInterval, scrapeTimeout from here
  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'tsb'
        honor_timestamps: true
        honor_labels: true
        metrics_path: '/metrics'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - tsb
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
            action: keep
            regex: otel-collector;prometheus
      - job_name: 'kubernetes-nodes'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        metrics_path: /metrics/cadvisor
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

grafana:
  replicas: 1
  image:
    repository: grafana/grafana
    tag: 9.1.7
  service:
    type: ClusterIP
    port: 3000
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
