{
 "title": "Control Plane Operator metrics",
 "description": "Dashboard to show the status of control plane operator metrics.",
 "tags": [
  "control plane",
  "tsb",
  "control plane tokens"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Control Plane Mode",
   "type": "table",
   "description": "This panel represents the control plane mode configured in the control plane cluster.\n\nPossible values are:\n- CONTROL(Default)\n- OBSERVE",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "control_plane_mode == 1" }
   ]
  },
  { "title": "Control Plane Token Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Closest Token To Expire",
   "type": "stat",
   "description": "\nThe 10 clusters that have a token that will expire the soonest.  \nTokens are rotated halfway through their validity period. By default, tokens are valid for one hour, so they are rotated 30 minutes after creation. If a cluster's time is displayed in red or with a negative value, it indicates that at least one token has expired without being rotated. In such cases, please review the \"Token Rotations Execution Failed\" chart to check for any failed token rotation attempts.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(token_expiration_timestamp{cluster_name=~\"${cluster}\"}[$__rate_interval])) by (cluster_name) - time()",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Clusters Not Validating Tokens",
   "type": "stat",
   "description": "Each cluster should validate all its token every 60 seconds.\nIf a cluster shows up it means that the last time it validated the tokens and reported the result is over 120 seconds ago. \n\nThis doesn't necessarily mean that any token is invalid or is not being rotated properly.\nFor example, the metrics may not have been reported correctly or in a timely manner, \nor that there is a problem with the TSB Control Plane operator.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time() - max_over_time(last_tokens_validation_timestamp{cluster_name=~\"${cluster}\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Valid Tokens",
   "type": "bargauge",
   "description": "Number of valid control plane tokens.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(valid_tokens{cluster_name=~\"${cluster}\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Token Rotation Executions",
   "type": "timeseries",
   "description": "Number of token rotation executions. An execution doesn't necessarily mean than a token has been rotated as they might still be valid.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(token_rotation_executions_count_total{cluster_name=~\"${cluster}\"}[$__rate_interval])) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Token Rotation Execution Failed",
   "type": "timeseries",
   "description": "Number of failed token rotation executions.\nIf there are errors in this chart it means that the token could not be rotated.\nPlease check the TSB Control Plane operator logs to find the cause. Use the following command:\nkubectl logs -n istio-system -l name=tsb-operator --tail=-1 | grep \"token rotation failed, retrying in\"",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(token_rotation_executions_count_total{cluster_name=~\"${cluster}\", status=\"failed\"}[5m])) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Tokens Exceeded Rotation Time",
   "type": "bargauge",
   "description": "Number of control plane tokens that exceeded their rotation time.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(token_exceeded_rotation_time{cluster_name=~\"${cluster}\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Tokens Rotated Successfully.",
   "type": "timeseries",
   "description": "Number of tokens that have been rotated successfully.\nIf the values are 0 it might mean that the token rotation execution is failing or that TSB Control Plane operator is not even running.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(token_rotations_count_total{cluster_name=~\"${cluster}\", status=\"success\"}[$__rate_interval])) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Failed Tokens to Rotate.",
   "type": "timeseries",
   "description": "Number of tokens that have been could not be rotated.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(token_rotations_count_total{cluster_name=~\"${cluster}\", status=\"failed\"}[$__rate_interval])) by(cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Tokens Exceeded Rotation Timeline",
   "type": "state-timeline",
   "description": "Number of control plane tokens that exceeded their rotation time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "max(max_over_time(token_exceeded_rotation_time{cluster_name=~\"${cluster}\"}[$__rate_interval])) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Valid Tokens Timeline",
   "type": "state-timeline",
   "description": "Number of valid control plane tokens.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(valid_tokens{cluster_name=~\"${cluster}\"}) by (cluster_name)",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Invalid Tokens",
   "type": "stat",
   "description": "Number of invalid control plane tokens grouped by the reason.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (reason) (invalid_tokens{cluster_name=~\"$cluster\"})",
     "legendFormat": "{{reason}}"
    },
    {
     "expr": "sum by (__name__) (token_missing_rotate_at_annotation{cluster_name=~\"$cluster\"})",
     "legendFormat": "token-missing-rotate-at-annotation"
    }
   ]
  }
 ]
}