{
 "title": "Istio Operational Status",
 "description": "Operational metrics for istiod health.",
 "tags": [
  "tsb",
  "istiod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } },
   { "name": "istio_revision", "label": "Istio Revision", "query": { "query": "label_values(istio_revision)" } }
  ]
 },
 "panels": [
  {
   "title": "At a Glance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected Envoys",
   "type": "stat",
   "description": "Count of Envoys connected to istiod. This should represent the total number of endpoints in the selected cluster.\n\nIf this number significantly decreases for longer than 5 minutes without an obvious reason (e.g. a scale-down event) then you should investigate. This may indicate that Envoys have been disconnected from istiod and are unable to reconnect.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pilot_xds{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Total Error Rate",
   "type": "stat",
   "description": "The total error rate for Istio when configuring Envoy, including generation and transport errors.\n\nAny errors (current and historic) should be investigated using the more detailed split below.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_write_timeout{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) +\nsum(rate(pilot_total_xds_internal_errors{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) +\nsum(rate(pilot_total_xds_rejects{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) +\nsum(rate(pilot_xds_expired_nonce{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) +  \nsum(rate(pilot_xds_push_context_errors{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) +  \nsum(rate(pilot_xds_pushes{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\",type=~\".*_senderr\"}[1m]))\nOR on() vector(0)"
    }
   ]
  },
  {
   "title": "Median Proxy Convergence Time",
   "type": "stat",
   "description": "The median (50th percentile) delay between istiod receiving configuration changes and the proxy receiving all required configuration in the selected cluster. This number indicates how stale the proxy configuration is. As this number increases, it may start to impact application traffic.\n\nThis number is typically in the hundreds of milliseconds. In small clusters, this number may be zero.\n\nIf this number creeps up to 30s for an extended period, istiod likely needs to be scaled out (or up).",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Time to Root CA expiration",
   "type": "stat",
   "description": "Time remaining until expiration of the Istiod root CA (displayed as 'days hours:minutes:seconds'). The value will turn yellow (warning) when the time to expiration is less than 6 month, and will turn red (critical) when it expires in less than a month.",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citadel_server_root_cert_expiry_timestamp{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to cert chain expiration",
   "type": "stat",
   "description": "Time remaining until expiration of the Istiod certificate chain (the certificates istiod uses to sign workload certificates). The value will turn yellow (warning) when the time to expiration is less than 6 month, and will turn red (critical) when it expires in less than a month.\n\nIf this shows no value, it means your istiod instances are using a self-signed certificate or a root CA certificate to issue workload certificates, instead of using an intermediate CA. If that is the case, this panel is meaningless to you, but you should consider using an intermediate CA for your istio control planes.",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citadel_server_cert_chain_expiry_timestamp{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Envoy Filter Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Applied Envoy Filters",
   "type": "gauge",
   "description": "Number of successfully applied Envoy Filters in the cluster.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pilot_envoy_filter_status{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\",result=\"applied\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errored Envoy Filters",
   "type": "gauge",
   "description": "Number of Envoy Filters in the cluster that failed to apply.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pilot_envoy_filter_status{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\",result=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy Filter status",
   "type": "table",
   "description": "Status of each Envoy Filter in the cluster (applied/error).",
   "gridPos": { "h": 8, "w": 15, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "pilot_envoy_filter_status{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Istiod Push Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Istiod Push Rate",
   "type": "graph",
   "description": "The rate of istiod pushes to Envoy grouped by discovery service. Istiod pushes clusters (CDS), endpoints (EDS), listeners (LDS) or routes (RDS) any time it receives a configuration change. \n\nChanges are triggered by a user interacting with TSB or a change in infrastructure such as a new endpoint (service instance/pod) creation.\n\nIn small relatively static clusters these values can be zero most of the time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_xds_pushes{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\",type=~\"cds|eds|rds|lds\"}[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Istiod Error Rate",
   "type": "graph",
   "description": "The different error rates for Istio during general operations. Including the generation and distribution of Envoy configuration.\n\n`pilot_xds_write_timeout`\nRate of connection timeouts between Envoy and istiod. This number indicates that an Envoy has taken too long to acknowledge a configuration change from Istio. An increase in these errors typically indicates network issues, envoy resource limits or istiod resource limits (usually cpu)\n\n`pilot_total_xds_internal_errors`\nRate of errors thrown inside istiod whilst generating Envoy configuration. Check the istiod logs for more details if you see internal errors.\n\n`pilot_total_xds_rejects`\nRate of rejected configuration from Envoy. Istio should never produce any invalid Envoy configuration so any errors here warrants investigation, starting with the istiod logs.\n\n`pilot_xds_expired_nonce`\nRate of expired nonces from Envoys. This number indicates that an Envoy has responded to the wrong request sent from Istio. An increase in these errors typically indicates network issues (saturation or partition), Envoy resource limits or istiod resource limits (usually cpu).\n\n`pilot_xds_push_context_errors`\nRate of errors setting a connection with an Envoy instance. An increase in these errors typically indicates network issues (saturation or partition), Envoy resource limits or istiod resource limits (usually cpu). Check istiod logs for further details.\n\n`pilot_xds_pushes`\nRate of transport errors sending configuration to Envoy.  An increase in these errors typically indicates network issues (saturation or partition), Envoy resource limits or istiod resource limits (usually cpu).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pilot_xds_write_timeout{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Write Timeouts"
    },
    {
     "expr": "sum(rate(pilot_total_xds_internal_errors{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Internal Errors"
    },
    {
     "expr": "sum(rate(pilot_total_xds_rejects{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Config Rejections"
    },
    {
     "expr": "sum(rate(pilot_xds_expired_nonce{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Expired Nonce"
    },
    {
     "expr": "sum(rate(pilot_xds_push_context_errors{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Push Context Errors"
    },
    {
     "expr": "sum(rate(pilot_xds_pushes{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\",type=~\".*_senderr\"}[1m])) by (type)",
     "legendFormat": "Send Failures {{ type }}"
    }
   ]
  },
  {
   "title": "Proxy Convergence Time",
   "type": "graph",
   "description": "The delay between an istiod receiving configuration changes and a proxy receiving all required configuration in the cluster. Broken down by percentiles.\n\nThis number indicates how stale the proxy configuration is. As this number increases it may start to affect application traffic.\n\nThis number is typically in the hundreds of milliseconds. If this number creeps up to 30s for an extended period of time, it is likely that istiod needs to be scaled out (or up) as it is likely pinned up against its CPU limits.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(pilot_proxy_convergence_time_bucket{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket{cluster_name=\"$cluster\"}[1m])) by (le))",
     "legendFormat": "P99.9"
    }
   ]
  },
  {
   "title": "Webhooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Configuration Validation",
   "type": "graph",
   "description": "Success and failure rate of `istio` configuration validation requests. This is triggered when TSB configuration is created or updated.\n\nAny failures here should be investigated in the istiod and `edge` logs.\n\nIf there are TSB configuration changes being made that affect the selected cluster and the success number is zero then there is an issue with configuration propagation. Check the XCP `edge` logs to debug further.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(galley_validation_passed{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Validations (Success)"
    },
    {
     "expr": "sum(rate(galley_validation_failed{cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "Validation (Failure)"
    }
   ]
  },
  {
   "title": "Sidecar Injection",
   "type": "graph",
   "description": "Rate of sidecar injection requests. Sidecar injection is triggered whenever a new instance/pod is created.\n\nAny errors displayed here should be investigated further by checking the istiod logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidecar_injection_success_total{cluster_name=\"$cluster\",istio_revision=\"$istio_revision\"}[1m]))",
     "legendFormat": "Injections (Success)"
    },
    {
     "expr": "sum(rate(sidecar_injection_failure_total{cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "Injections (Failure)"
    }
   ]
  }
 ]
}