{
 "title": "OAP Operational Status",
 "description": "Operational metrics to indicate Tetrate Service Bridge OAP stack health.",
 "tags": [
  "tsb",
  "observability",
  "oap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "OAP Request Rate",
   "type": "timeseries",
   "description": "The request rate to OAP, by status.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code_class) (rate(envoy_cluster_upstream_rq_xx_total{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m]))",
     "legendFormat": "envoy_response_code_class={{envoy_response_code_class}}"
    }
   ]
  },
  {
   "title": "OAP Request Latency",
   "type": "timeseries",
   "description": "The OAP, request latency.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"oap-grpc\", plane=\"management\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "OAP Aggregation Request Rate",
   "type": "timeseries",
   "description": "OAP Aggregation Request Rate, by type:\n- central aggregation service handler received\n- central application aggregation received\n-  central service aggregation received",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(central_aggregation_handler_total[1m]))",
     "legendFormat": "central aggregation handler"
    },
    {
     "expr": "sum(rate(central_app_aggregation_total[1m]))",
     "legendFormat": "central app aggregation"
    },
    {
     "expr": "sum(rate(central_service_aggregation_total[1m]))",
     "legendFormat": "central service aggregation"
    }
   ]
  },
  {
   "title": "OAP Aggregation Rows",
   "type": "timeseries",
   "description": "Cumulative rate of rows in OAP aggreagation.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(metrics_aggregation_total{plane=\"management\"}[1m]))",
     "legendFormat": "number of rows"
    }
   ]
  },
  {
   "title": "OAP Mesh Analysis Latency",
   "type": "timeseries",
   "description": "The process latency of OAP service mesh telemetry streaming process.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mesh_analysis_latency_bucket{plane=\"control\", component=\"oap\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mesh_analysis_latency_bucket{plane=\"control\", component=\"oap\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(mesh_analysis_latency_bucket{plane=\"control\", component=\"oap\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(mesh_analysis_latency_bucket{plane=\"control\", component=\"oap\"}[1m])) by (le))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "OAP Zipkin Receiver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "OAP Zipkin Trace Rate",
   "type": "timeseries",
   "description": "The OAP Zipkin processing trace rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(trace_in_latency_count{protocol='zipkin-http',plane='control'}[1m]))",
     "legendFormat": "zipkin_traces"
    }
   ]
  },
  {
   "title": "OAP Zipkin Trace Latency",
   "type": "timeseries",
   "description": "The OAP trace processing latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(trace_in_latency_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(trace_in_latency_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(trace_in_latency_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(trace_in_latency_bucket[5m])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(trace_in_latency_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "OAP Zipkin Trace Error Rate",
   "type": "graph",
   "description": "The OAP Zipkin processing trace error rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trace_analysys_error_count{protocol='zipkin-http',plane='control'}[1m]))",
     "legendFormat": "zipkin_errors"
    }
   ]
  },
  {
   "title": "JVM Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "description": "Numbed of threads in OAP JVM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{component=\"oap\", plane=\"management\"})",
     "legendFormat": "current"
    },
    {
     "expr": "sum(jvm_threads_daemon{component=\"oap\", plane=\"management\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum(jvm_threads_peak{component=\"oap\", plane=\"management\"})",
     "legendFormat": "peak"
    },
    {
     "expr": "sum(jvm_threads_deadlocked{component=\"oap\", plane=\"management\"})",
     "legendFormat": "deadlocked"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "description": "JVM Memory stats of OAP JVM instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (area, instance) (jvm_memory_bytes_max{component=\"oap\", plane=\"management\"})",
     "legendFormat": "{{area}}/{{instance}} max"
    },
    {
     "expr": "sum by (area, instance) (jvm_memory_bytes_used{component=\"oap\", plane=\"management\"})",
     "legendFormat": "{{area}}/{{instance}} used"
    }
   ]
  }
 ]
}